---
title: "Test for networks of scholar ids"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(scholar)
library(igraph)
library(ggraph)
library(tidygraph)
library(networkD3)
library(googlesheets4)
```


Rmd with concept test for scholar network


## Network for Brian Maitner, Cory Merow, and Derek Corcoran

```{r, echo = FALSE, out.width= "100%"}
Ids <- read_sheet("https://docs.google.com/spreadsheets/d/1jc8QMTADx18r_l_FZqVrGMaoOb3nIqXyYiGaHk1MvvQ")

Ids <- Ids$`User (After user= up to &hl)`
coauthor_network <- Ids %>% 
  purrr::map(get_coauthors) %>% 
  reduce(bind_rows)
```


```{r, echo = FALSE, out.width= "100%"}
coauthor_network <- coauthor_network %>% 
  mutate(coauthors = ifelse(str_detect(coauthors,"Pdf"), "Brian J. Enquist", coauthors), author = ifelse(str_detect(author,"Pdf"), "Brian J. Enquist", author)) %>% dplyr::filter(!str_detect(author, "Sort By"),!str_detect(coauthors, "Sort By"))

plot_coauthors(coauthor_network, size_labels = 4) + ggtitle("")
```

```{r}
p <- simpleNetwork(coauthor_network, height="100px", width="100px")
p
```
  
  